from datetime import datetime
import json
from typing import Any, Dict, Optional
from memory import (
    build_evidence_context,
    get_session_context,
    save_evidence,
    save_last_user_query,
)
from worker_agents import (
    retriever_agent,
    run_model,
    verifier_agent,
    writer_agent,
)
from worker_agents.verifier_agent import parse_evidence_status

"""
Orchestrator 
=====================================================================================
In the orchestrator tool schema there are 4 tools defined:
3 agentic tools: (Retriever, Writer and Verifier).
and 1 non agentic tool(reuse_cached_evidence)

1. reuse_cached_evidence is used when there is stored evidence in memory
relevant to the current query. It prevents retrieving information that
has already been gathered for a similar query. It is a non-agent tool.

2. call_retriever_agent is the worker agent to retrieve information from a set of
documents or the web or both depending on the query.

3. call_writer_agent is the worker agent to write a report based on what was retrieved
from the retriever agent.
4. call_verifier_agent is the worker agent to verify the claims in the content generated by the writer agent
and return the final report.

Depending on the query the orchestrator can reuse stored evidence from memory if
relevant information is already available, or retrieve evidence first and then
proceed to writing and verification.
"""

# Tool schema used by the orchestrator to coordinate worker agents.
ORCHESTRATOR_TOOL_SCHEMAS = [
    {
        "type": "function",
        "name": "reuse_cached_evidence",
        "description": (
            """Activate the cached evidence from the previous turn when it is still
            clearly and directly relevant to the current query. Prefer this for
            follow-up questions that rely on the same evidence. Do not use it when
            the user asks for a different detail, angle, missing information, or a
            new topic."""
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "description": "Short explanation of why the cached evidence is still directly relevant.",
                }
            },
            "required": ["reason"],
            "additionalProperties": False,
        },
    },
    {
        "type": "function",
        "name": "call_retriever_agent",
        "description": (
            """Gather evidence for the current query. Use this for evidence-request
            turns when cached evidence is missing, not clearly relevant, or the
            user asks for a different detail, angle, or missing information. This
            worker decides whether to use uploaded documents, web search, or both."""
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Self-contained evidence request for the retriever. Rewrite follow-up questions to include omitted subject details when needed.",
                }
            },
            "required": ["query"],
            "additionalProperties": False,
        },
    },
    {
        "type": "function",
        "name": "call_writer_agent",
        "description": (
            """Write the report using the active retrieved evidence. Use only after
            evidence has been activated for the current turn."""
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "user_query": {
                    "type": "string",
                    "description": "The current user request to answer.",
                },
                "evidence_text": {
                    "type": "string",
                    "description": "The active formatted evidence to ground the draft.",
                },
            },
            "required": ["user_query", "evidence_text"],
            "additionalProperties": False,
        },
    },
    {
        "type": "function",
        "name": "call_verifier_agent",
        "description": (
            """Verify whether the report draft is grounded in the active evidence and
            return the final report. Use only after a writer draft exists and
            evidence is active for the current turn."""
        ),
        "parameters": {
            "type": "object",
            "properties": {
                "written_draft": {
                    "type": "string",
                    "description": "The writer agent's draft to verify.",
                },
                "evidence_text": {
                    "type": "string",
                    "description": "The active formatted evidence used to check the draft.",
                },
            },
            "required": ["written_draft", "evidence_text"],
            "additionalProperties": False,
        },
    },
    {
        "type": "function",
        "name": "finish_research",
        "description": (
            """The research is complete and you have a final verified answer.
            Use this tool to return the final answer to the user. Call this
            when you have evidence, a writer draft, and a verifier output —
            OR when you have exhausted all reasonable re-retrieval attempts
            and have at least a partial verified answer. Do NOT call this
            unless you have evidence and a draft that has been verified, or
            unless re_retrieve_rounds has reached 2."""
        ),
        "strict": True,
        "parameters": {
            "type": "object",
            "properties": {
                "reason": {
                    "type": "string",
                    "description": (
                        "Brief explanation of why research is complete. "
                        "E.g., 'Verified report is grounded in retrieved evidence.' "
                        "or 'Exhausted re-retrieval rounds; returning best available answer.'"
                    ),
                },
            },
            "required": ["reason"],
            "additionalProperties": False,
        },
    },
]

# Instructions guiding the LLM's behavior in Orchestrator
ORCHESTRATOR_INSTRUCTIONS = (
    f"""
    You coordinate three worker agents: retriever, writer, and verifier.
    You also have a finish_research tool to return the final answer.

    RULES — FOLLOW THESE EXACTLY:
    1. For ANY factual, research, or informational question (about topics, concepts, models, papers, products, companies, people, current events), you MUST call available tools. Do NOT answer from your own knowledge.
    2. For greetings, thanks, or brief conversational replies, respond in one short sentence WITHOUT calling any tools.
    3. For clearly non-research requests (coding help, math, unrelated tasks), reply: "I'm a research assistant focused on answering questions about the active documents and on researching the web when needed." WITHOUT calling any tools.

    WORKFLOW (follow this order strictly):
    - First: gather evidence with call_retriever_agent (or reuse_cached_evidence if previous evidence is directly relevant)
    - Then: write a draft with call_writer_agent using the evidence
    - Then: verify the draft with call_verifier_agent
    - If verifier reports gaps AND re_retrieve_rounds < 2: go back to gathering evidence with call_retriever_agent, then repeat write → verify
    - Once verification is done (or re_retrieve_rounds reaches 2): call finish_research to return the answer

    CRITICAL: Do NOT answer directly without calling tools first. Every research question requires evidence retrieval before any answer.

    State awareness:
    - If the state indicates needs_more_evidence is True and gap_queries are provided, call call_retriever_agent with a query that specifically addresses those gaps. Do NOT call writer or verifier yet.
    - If re_retrieve_rounds has reached 2, do NOT re-retrieve again even if gaps remain. Proceed to write and verify with whatever evidence is available, then finish.
    - Once you have a verified answer (verifier output is available), call finish_research to return it. Do NOT keep calling other tools after the verifier has run.
    - If you cannot retrieve evidence or the verifier found significant gaps and re_retrieve_rounds is at 2, call finish_research with the draft or partial answer.
    - If you have evidence and a writer draft but the verifier has NOT yet run, call call_verifier_agent first — do NOT call finish_research yet.
    """
)

# Format the current orchestration state for the model.
def build_orchestrator_prompt_context(state: dict[str, Any]) -> str:
    evidence_context = build_evidence_context(state["evidence_json"])
    status = state.get("verification_status") or {}
    return (
        f"- current_date: {state['current_date']}\n"
        f"- last_user_query: {state['last_user_query'] or 'None'}\n"
        f"- cached_query: {state['cached_query'] or 'None'}\n"
        f"- retrieval_attempted: {state['retrieval_attempted']}\n"
        f"- has_written_draft: {bool(state['written_draft'])}\n"
        f"- has_verification: {bool(state['verification'])}\n"
        f"- needs_more_evidence: {state['needs_more_evidence']}\n"
        f"- re_retrieve_rounds: {state['re_retrieve_rounds']}\n"
        f"- gap_queries: {state['gap_queries']}\n\n"
        f"Cached evidence summary:\n{state['cached_evidence_summary']}\n\n"
        f"Current evidence summary:\n{evidence_context['summary']}\n\n"
        f"Verification status:\n"
        f"  confidence: {status.get('confidence', 'unknown')}\n"
        f"  gaps: {status.get('gaps', [])}\n"
        f"  re_retrieve: {status.get('re_retrieve', False)}"
    )

"""
Helper memory handler functions used in the Orchestrator
=====================================================================
For a given session id in the orchestrator the memory helper functions work like this:

- save_evidence: saves the latest retrieved evidence for the session so it can
be reused for followup questions when still relevant.

- save_last_user_query: saves the latest user query for followup questions.

- build_evidence_context: parses saved evidence_json and returns a summary evidence status, and formatted evidence.
- get_session_context: returns the latest user query and cached evidence
- context for the session to support followup questions and evidence reuse.
"""

def orchestrator_agent(
    user_query: str,
    session_id: str = "default",
    verbose: bool = True,
    endpoint: Optional[str] = None,
    api_key: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Execute the orchestrator agent.
    
    Args:
        user_query: The user's query to orchestrate
        session_id: Session ID for memory persistence
        verbose: Whether to print debug information
        endpoint: Optional custom endpoint URL
        api_key: Optional custom API key
        
    Returns:
        Dict with the orchestration state and results
    """
    
    # Load session context for follow-up questions and cached evidence reuse.
    session_context = get_session_context(session_id)
    cached_evidence_json = session_context["cached_evidence_json"]

    # Current date to support time-aware decisions.
    current_date = datetime.now().astimezone().date().isoformat()

    state = {
        "user_query": user_query,
        "current_date": current_date,
        "last_user_query": session_context["last_user_query"],
        "cached_query": session_context["cached_query"],
        "cached_evidence_summary": session_context["cached_evidence_summary"],
        "retrieval_attempted": False,
        "evidence_json": "",
        "written_draft": "",
        "verification": "",
        "verification_status": {},
        "needs_more_evidence": False,
        "gap_queries": [],
        "re_retrieve_rounds": 0,
        "finish_reason": "",              # NEW: reason from finish_research call
        "final_answer": "",
    }
    evidence_already_active = "Evidence is already active for this turn; proceed to writing."

    response = run_model(
        instructions=ORCHESTRATOR_INSTRUCTIONS,
        reasoning_effort="low",
        input_data=(
            f"User query: {user_query}\n\n"
            f"Current state:\n{build_orchestrator_prompt_context(state)}"
        ),
        tools=ORCHESTRATOR_TOOL_SCHEMAS,
        agent_name="orchestrator",
        endpoint=endpoint,
        api_key=api_key,
    )

    # Allow up to 10 orchestration rounds before stopping.
    for _ in range(10):
        iteration = _ + 1
        if verbose:
            print(f"\n{'='*60}")
            print(f"[ORCHESTRATOR] Iteration {iteration}/10")
            print(f"  state evidence_json len: {len(state['evidence_json'])}")
            print(f"  state written_draft len: {len(state.get('written_draft', ''))}")
            print(f"  state verification len: {len(state.get('verification', ''))}")
            print(f"  needs_more_evidence: {state['needs_more_evidence']}")
            print(f"  re_retrieve_rounds: {state['re_retrieve_rounds']}")
            print(f"  gap_queries: {state['gap_queries']}")
            print(f"  verification_status: {state.get('verification_status', {})}")
            print(f"{'='*60}")
        function_calls = [item for item in response.output if item.type == "function_call"]

        # If the model does not request any tools, return its direct reply.
        if not function_calls:
            state["final_answer"] = response.output_text or "I couldn't find enough evidence to answer that."
            if verbose:
                print(f"[ORCHESTRATOR] EARLY RETURN: {state['final_answer'][:100]}")
            save_last_user_query(session_id, user_query)
            return state

        if verbose and function_calls:
            for fc in function_calls:
                print(f"[ORCHESTRATOR] LLM called: {fc.name}({fc.arguments})")

        tool_outputs = []

        for call in function_calls:
            name = call.name
            args = json.loads(call.arguments)

            if name == "reuse_cached_evidence":
                if state["evidence_json"]:
                    output = evidence_already_active
                elif cached_evidence_json:
                    if verbose:
                        print("[ORCHESTRATOR] Reusing cached evidence.")
                    state["evidence_json"] = cached_evidence_json
                    state["cached_query"] = session_context["cached_query"]
                    output = f"Reused cached evidence: {args['reason']}"
                else:
                    output = "No cached evidence is available to reuse."
                    # No cached evidence and no current evidence — skip ahead
                    if not state["evidence_json"]:
                        if verbose:
                            print("[ORCHESTRATOR] No cached or current evidence. Skipping to finish.")
                        state["final_answer"] = (
                            "I couldn't find relevant evidence in the uploaded documents or via web search for this query. "
                            "Try asking about a topic covered in your documents, or upload a relevant document."
                        )
                        save_last_user_query(session_id, user_query)
                        return state

            elif name == "call_retriever_agent":
                # DEBUG: log which branch will fire
                if state["evidence_json"] and not state["needs_more_evidence"]:
                    print("[ORCHESTRATOR DEBUG] call_retriever_agent → STEP 1 (evidence already active)")
                elif state["needs_more_evidence"] and state["gap_queries"]:
                    print("[ORCHESTRATOR DEBUG] call_retriever_agent → STEP 2 (gap re-retrieval)")
                elif state["needs_more_evidence"]:
                    print("[ORCHESTRATOR DEBUG] call_retriever_agent → STEP 3 (gap flag, proceed)")
                elif state["retrieval_attempted"]:
                    print("[ORCHESTRATOR DEBUG] call_retriever_agent → STEP 4 (already attempted)")
                else:
                    print("[ORCHESTRATOR DEBUG] call_retriever_agent → STEP 5 (initial retrieval)")
                # STEP 1: If evidence is already active and no re-retrieval needed, proceed to writing
                if state["evidence_json"] and not state["needs_more_evidence"]:
                    output = evidence_already_active
                
                # STEP 2: Gap-driven re-retrieval (verifier found evidence gaps)
                elif state["needs_more_evidence"] and state["gap_queries"]:
                    if verbose:
                        print("[ORCHESTRATOR] Performing gap-driven re-retrieval...")
                    state["re_retrieve_rounds"] += 1
                    state["needs_more_evidence"] = False
                    gap_context = (
                        f"Follow-up retrieval to address evidence gaps: {state['gap_queries']}. "
                        f"Previous evidence is already active; gather complementary or additional evidence."
                    )
                    evidence_pack = retriever_agent(
                        gap_context,
                        last_user_query=state["last_user_query"],
                        verbose=verbose,
                    )
                    output = evidence_pack.model_dump_json()
                    evidence_context = build_evidence_context(output)
                    if evidence_context["has_evidence"]:
                        try:
                            new_ev_json = json.loads(output)
                        except (json.JSONDecodeError, TypeError):
                            print("[ORCHESTRATOR] Failed to parse retriever output as JSON, skipping merge")
                            new_ev_json = {}

                        try:
                            existing_ev = json.loads(state["evidence_json"]) if state.get("evidence_json") else {}
                        except (json.JSONDecodeError, TypeError):
                            existing_ev = {}

                        if not new_ev_json:
                            print("[ORCHESTRATOR] No evidence in gap retriever output, skipping merge")
                            state["written_draft"] = ""
                            state["verification"] = ""
                            continue

                        # Only proceed with merge if both are valid dicts
                        if not isinstance(new_ev_json, dict) or not isinstance(existing_ev, dict):
                            print("[ORCHESTRATOR] Invalid evidence structure, skipping merge")
                            state["written_draft"] = ""
                            state["verification"] = ""
                            continue

                        new_ev_json["query"] = gap_context
                        has_docs = bool(new_ev_json.get("document_evidence", {}).get("chunks"))
                        has_web = bool(new_ev_json.get("web_evidence", {}).get("results"))
                        if has_docs and has_web:
                            new_ev_json["route_used"] = "both"
                        elif has_docs:
                            new_ev_json["route_used"] = "documents"
                        elif has_web:
                            new_ev_json["route_used"] = "web"
                        else:
                            new_ev_json["route_used"] = "none"

                        # Merge document chunks (dedup by chunk_id)
                        new_doc_chunks = new_ev_json.get("document_evidence", {}).get("chunks", [])
                        existing_doc_evidence = existing_ev.setdefault("document_evidence", {"query": "", "chunks": []})
                        existing_doc_ids = {c.get("chunk_id") for c in existing_doc_evidence.get("chunks", [])}
                        for chunk in new_doc_chunks:
                            if chunk.get("chunk_id") not in existing_doc_ids:
                                existing_doc_evidence["chunks"].append(chunk)

                        # Merge web results (dedup by url)
                        new_web = new_ev_json.get("web_evidence", {}).get("results", []) or []
                        existing_web = existing_ev.setdefault("web_evidence", {"query": "", "results": []})
                        # Handle case where existing_web is None or has results=None
                        if existing_web is None:
                            existing_web = {"query": "", "results": []}
                            existing_ev["web_evidence"] = existing_web
                        existing_web_urls = {r.get("url", "") for r in (existing_web.get("results") or [])}
                        
                        # Also handle document_evidence being None
                        existing_doc_evidence = existing_ev.setdefault("document_evidence", {"query": "", "chunks": []})
                        if existing_doc_evidence is None:
                            existing_doc_evidence = {"query": "", "chunks": []}
                            existing_ev["document_evidence"] = existing_doc_evidence
                        for result in new_web:
                            if result.get("url", "") not in existing_web_urls:
                                existing_web["results"].append(result)

                        state["evidence_json"] = json.dumps(existing_ev)
                        state["cached_evidence_summary"] = evidence_context["summary"]
                    else:
                        output = evidence_pack.summary or "Retriever could not gather additional evidence."
                    state["written_draft"] = ""
                    state["verification"] = ""
                    state["verification_status"] = {}
                    state["retrieval_attempted"] = True
                    output = f"Re-retrieved evidence for gaps. New evidence accumulated."
                
                # STEP 3: Gap flagged but no queries — proceed to write
                elif state["needs_more_evidence"]:
                    state["needs_more_evidence"] = False
                    state["gap_queries"] = []
                    output = "Proceeding to write with available evidence."
                
                # STEP 4: Already retrieved this turn — skip
                elif state["retrieval_attempted"]:
                    output = "Retrieval has already been attempted for this turn."
                
                # STEP 5: Initial retrieval — gather evidence
                else:
                    state["retrieval_attempted"] = True
                    if verbose:
                        print("[ORCHESTRATOR] Initializing Retriever Agent...")
                    evidence_pack = retriever_agent(
                        args["query"].strip() or state["user_query"],
                        last_user_query=state["last_user_query"],
                        verbose=verbose,
                    )
                    output = evidence_pack.model_dump_json()

                    # DEBUG: print the entire JSON structure to diagnose parsing
                    try:
                        parsed = json.loads(output)
                        print(f"[ORCHESTRATOR DEBUG] evidence_pack.model_dump() keys: {list(parsed.keys())}")
                        print(f"[ORCHESTRATOR DEBUG] document_evidence type: {type(parsed.get('document_evidence')).__name__}, value preview: {str(parsed.get('document_evidence'))[:300]}")
                    except Exception as e:
                        print(f"[ORCHESTRATOR DEBUG] Could not re-parse output: {e}")

                    # DEBUG: log what the retriever actually returned
                    print(f"[ORCHESTRATOR DEBUG] Retriever returned: query='{evidence_pack.query}', route='{evidence_pack.route_used}', summary='{evidence_pack.summary[:100]}...'")
                    doc_chunks = len(evidence_pack.document_evidence.get("chunks", [])) if evidence_pack.document_evidence else 0
                    web_results = len(evidence_pack.web_evidence.get("results", [])) if evidence_pack.web_evidence else 0
                    print(f"[ORCHESTRATOR DEBUG] Retriever found: {doc_chunks} doc chunks, {web_results} web results")

                    # Check evidence using the Pydantic model as source of truth
                    has_docs = bool(evidence_pack.document_evidence and evidence_pack.document_evidence.get("chunks"))
                    has_web = bool(evidence_pack.web_evidence and evidence_pack.web_evidence.get("results"))

                    if has_docs or has_web:
                        # Evidence found — store it and continue normal flow
                        state["evidence_json"] = output
                        state["cached_query"] = state["user_query"]
                        save_evidence(session_id, state["user_query"], output)
                        print(f"[ORCHESTRATOR DEBUG] SET state['evidence_json'] length: {len(output)} chars")
                        evidence_context = build_evidence_context(output)
                        state["cached_evidence_summary"] = evidence_context["summary"]
                    else:
                        # NO EVIDENCE FOUND — skip writer/verifier entirely, return directly
                        if verbose:
                            print("[ORCHESTRATOR] Retriever returned no evidence. Returning directly.")
                        state["final_answer"] = (
                            "I couldn't find relevant evidence in the uploaded documents or via web search for this query. "
                            "Try asking about a topic covered in your documents, or upload a relevant document."
                        )
                        save_last_user_query(session_id, user_query)
                        return state

            elif name in {"call_writer_agent", "call_verifier_agent"}:
                evidence_context = build_evidence_context(
                    state["evidence_json"],
                    include_formatted_evidence=True,
                )
                formatted_evidence = evidence_context["formatted_evidence"]
                if name == "call_writer_agent":
                    if not formatted_evidence:
                        print("[ORCHESTRATOR DEBUG] call_writer_agent → NO evidence (formatted_evidence empty)")
                    else:
                        print(f"[ORCHESTRATOR DEBUG] call_writer_agent → HAS evidence (formatted_evidence length: {len(formatted_evidence)})")
                    if not formatted_evidence:
                        output = "Cannot write yet because no retrieval evidence has been activated."
                        # No evidence — skip to finish immediately
                        if verbose:
                            print("[ORCHESTRATOR] No evidence for writer. Skipping to finish.")
                        state["final_answer"] = (
                            "I couldn't find relevant evidence in the uploaded documents or via web search for this query. "
                            "Try asking about a topic covered in your documents, or upload a relevant document."
                        )
                        save_last_user_query(session_id, user_query)
                        return state
                    else:
                        if verbose:
                            print("[ORCHESTRATOR] Initializing Writer Agent...")
                        output = writer_agent(
                            user_query=state["user_query"],
                            evidence_text=formatted_evidence,
                            verbose=verbose,
                        )
                        state["written_draft"] = output
                        if verbose:
                            print(f"[ORCHESTRATOR] Writer output (first 200 chars): {output[:200]}")
                            print(f"[ORCHESTRATOR] Writer output length: {len(output)} chars")
                        # Check if draft is too short — if so, flag for more evidence
                        draft_length = len(state.get("written_draft", ""))
                        if draft_length < 1500:
                            if verbose:
                                print(f"[ORCHESTRATOR] Draft too short ({draft_length} chars), will verify with depth check")
                        # If the writer produced almost nothing, evidence wasn't usable
                        if len(output.strip()) < 50:
                            if verbose:
                                print("[ORCHESTRATOR] Writer produced negligible output. Evidence wasn't usable.")
                            state["final_answer"] = (
                                "The retrieved evidence wasn't sufficient to write a meaningful answer. "
                                "The documents may not cover this topic. Try a different query or upload relevant documents."
                            )
                            save_last_user_query(session_id, user_query)
                            if verbose:
                                print(f"[ORCHESTRATOR] EARLY RETURN: {state['final_answer'][:100]}")
                            return state
                elif not state["written_draft"]:
                    output = "Cannot verify yet because no report draft exists."
                elif not formatted_evidence:
                    output = "Cannot verify yet because no retrieval evidence is active."
                else:
                    if verbose:
                        print("[ORCHESTRATOR] Initializing Verifier Agent...")
                    output = verifier_agent(
                        user_query=state["user_query"],
                        written_draft=state["written_draft"],
                        evidence_text=formatted_evidence,
                        verbose=verbose,
                    )
                    state["verification"] = output
                    if verbose:
                        print(f"[ORCHESTRATOR] Verifier output (first 200 chars): {output[:200]}")
                        parsed = parse_evidence_status(output)
                        print(f"[ORCHESTRATOR] Parsed evidence status: {parsed}")
                    # Parse gap status from verifier output
                    print(f"[ORCHESTRATOR DEBUG] Verifier output length: {len(output)} chars")
                    print(f"[ORCHESTRATOR DEBUG] Verifier output contains 'EVIDENCE_STATUS:': {'EVIDENCE_STATUS:' in output}")
                    print(f"[ORCHESTRATOR DEBUG] Verifier output contains '~~~': {'~~~' in output}")
                    # Show last 500 chars of verifier output for debugging
                    if len(output) > 500:
                        print(f"[ORCHESTRATOR DEBUG] Last 500 chars of verifier output:\n{output[-500:]}")
                    else:
                        print(f"[ORCHESTRATOR DEBUG] Full verifier output:\n{output}")
                    
                    parsed_status = parse_evidence_status(output)
                    
                    # If parser returned None, try to diagnose why
                    if not parsed_status:
                        print(f"[ORCHESTRATOR DEBUG] parse_evidence_status returned None")
                        # Quick manual check: try to find the block
                        start = output.find('EVIDENCE_STATUS:')
                        if start >= 0:
                            block = output[start:start+500]
                            print(f"[ORCHESTRATOR DEBUG] Found EVIDENCE_STATUS block preview:\n{block[:500]}")
                        else:
                            print(f"[ORCHESTRATOR DEBUG] No EVIDENCE_STATUS: found anywhere in verifier output")
                    if parsed_status:
                        state["verification_status"] = parsed_status
                        
                        # Direct coverage safeguard: force re-retrieval when:
                        # 1. Coverage is thin/moderate, OR
                        # 2. The depth override detected thin evidence (always takes precedence)
                        #    — the verifier is biased to say "comprehensive" on thin evidence
                        
                        cov = state["verification_status"].get('coverage', 'moderate')
                        has_depth_override = '[DEPTH OVERRIDE' in output
                        depth_override_triggered = False
                        
                        if cov in ('thin', 'moderate'):
                            depth_override_triggered = True
                            print(f"[ORCHESTRATOR] COVERAGE OVERRIDE: forcing re_retrieve=True (coverage={cov})")
                        elif has_depth_override:
                            # System detected thin evidence — trust the system over the LLM's inflated rating
                            depth_override_triggered = True
                            print(f"[ORCHESTRATOR] DEPTH OVERRIDE: forcing re_retrieve=True (system detected thin evidence)")
                        
                        if depth_override_triggered and not state["verification_status"].get('re_retrieve', False):
                            state["verification_status"]['re_retrieve'] = True
                            suggested = state["verification_status"].get('suggested_queries', [])
                            if not suggested:
                                suggested_queries = []
                                if 'THIN EVIDENCE' in output:
                                    suggested_queries.append('Search for deeper coverage: attention variants, optimization techniques, and broader applications')
                                if 'SINGLE-SOURCE' in output:
                                    suggested_queries.append('Search for additional documents or perspectives on the topic')
                                if 'NO_WEB_SEARCH' in output:
                                    suggested_queries.append('Use web_search to supplement document gaps with broader coverage')
                                state["verification_status"]['suggested_queries'] = suggested_queries
                        
                        if parsed_status.get("re_retrieve") and state["re_retrieve_rounds"] < 2:
                            state["needs_more_evidence"] = True
                            state["gap_queries"] = parsed_status.get("suggested_queries", [])
                            if verbose:
                                print(f"[ORCHESTRATOR] Verifier flagged {len(parsed_status.get('gaps', []))} gaps. Triggering gap-driven re-retrieval.")
                        else:
                            state["needs_more_evidence"] = False
                            state["gap_queries"] = []
                    else:
                        # Verifier returned without EVIDENCE_STATUS block — clear gap state
                        state["needs_more_evidence"] = False
                        state["gap_queries"] = []

            elif name == "finish_research":
                reason = args.get("reason", "Research complete.")
                state["finish_reason"] = reason
                if state["verification"]:
                    state["final_answer"] = state["verification"]
                    save_last_user_query(session_id, user_query)
                    if verbose:
                        print(f"[ORCHESTRATOR] EARLY RETURN: {state['final_answer'][:100]}")
                    return state
                elif state["written_draft"]:
                    state["final_answer"] = state["written_draft"]
                    save_last_user_query(session_id, user_query)
                    if verbose:
                        print(f"[ORCHESTRATOR] EARLY RETURN: {state['final_answer'][:100]}")
                    return state
                else:
                    state["final_answer"] = f"Research finished: {reason}"
                    save_last_user_query(session_id, user_query)
                    if verbose:
                        print(f"[ORCHESTRATOR] EARLY RETURN: {state['final_answer'][:100]}")
                    return state

            else:
                output = "Unknown tool name."

            tool_outputs.append(
                {
                    "type": "function_call_output",
                    "call_id": call.call_id,
                    "tool_name": call.name,
                    "output": output,
                }
            )

        # Log tool outputs for debugging
        for to in tool_outputs:
            if isinstance(to, dict) and "output" in to:
                print(f"[ORCHESTRATOR DEBUG] Tool output ({to['tool_name']}): {str(to['output'])[:200]}...")

        # Log what LLM returned this iteration
        if not function_calls:
            print(f"[ORCHESTRATOR DEBUG] LLM returned NO tool calls. Output text: {response.output_text[:200]}")
        else:
            for fc in function_calls:
                print(f"[ORCHESTRATOR DEBUG] LLM returned tool call: {fc.name} with {len(fc.arguments)} args")

        response = run_model(
            instructions=ORCHESTRATOR_INSTRUCTIONS,
            reasoning_effort="low",
            input_data=[
                *tool_outputs,
                {
                    "type": "message",
                    "role": "user",
                    "content": f"Updated state:\n{build_orchestrator_prompt_context(state)}",
                },
            ],
            tools=ORCHESTRATOR_TOOL_SCHEMAS,
            previous_response_id=response.id,
        )

    if state["verification"]:
        state["final_answer"] = state["verification"]
        save_last_user_query(session_id, user_query)
    elif state["written_draft"]:
        state["final_answer"] = state["written_draft"]
        save_last_user_query(session_id, user_query)
    else:
        state["final_answer"] = (
            "The research system encountered an issue processing your query. "
            "Please try again with a more specific question."
        )

    if verbose:
        print("[ORCHESTRATOR] Workflow complete.")
    return state